# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  param_fetcher_listener:  true
  body_listener: true
  #    allowed_methods_listener:  true
  #    routing_loader: false
  #       default_format: json
  #       include_format: false
  view:
    view_response_listener: true
    formats:
      json: true
  exception:
    enabled: true

  serializer:
    serialize_null: true

  #        codes:
  #            App\Exception\MyException: 403
  #        messages:
  #            App\Exception\MyException: Forbidden area.
  format_listener:
    rules:
      - { path: '^/', fallback_format: json, priorities: ['json'] }