vich_uploader:
    db_driver: orm # or mongodb or propel or phpcr
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    mappings:
        product_image:
            uri_prefix: '%images_directory%'
            upload_destination: '%kernel.project_dir%/public%images_directory% '
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\UniqidNamer