#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
  path: /api/login_check
  controller: App\Controller\UserController::getTokenUser

api_register:
  path: /api/